


# This file is a template, and might need editing before it works on your project.
# This file is a template demonstrating the `script` keyword.
# Learn more about this keyword here: https://docs.gitlab.com/ee/ci/yaml/README.html#script

# After committing this template, visit CI/CD > Jobs to see the script output.

stages:
    - deploy
deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - echo "$AWS_DEFAULT_REGION"
    - echo "$aws_access_key_id"
    - echo "$aws_secret_access_key"
    - echo "$S3_BUCKET"
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $aws_access_key_id
    - aws configure set aws_secret_access_key $aws_secret_access_key 
    - aws s3 sync . $S3_BUCKET
  only:
    - merge_requests





my_app_file_name:
 script:
 — apt-get update -qy
 — apt-get install -y python-dev python-pip
 — pip install -r requirements.txt
 — export MONGOHQ_URL=$MONGO_URL
 
production:
 type: deploy
 script:
 — apt-get update -qy
 — apt-get install -y ruby-dev
 — gem install dpl
 — dpl — provider=heroku — app=task-mgmt-app — api-key=$HEROKU_SECRET_KEY
 only:
 — master




 [app.py]:
    script:
        — apt-get update -qy
        — apt-get install -y python-dev python-pip
        — pip install -r requirements.txt

production:
    type: deploy
    script:
        — apt-get update -qy
        — apt-get install -y ruby-dev
        — gem install dpl
        — dpl — provider=heroku — app=[Heroku App Name] — api-key=$HEROKU_SECRET_KEY
    only:
        — master




cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy_qa
  - test_qa
  - deploy_prod

init:
  stage: init
  image: node:12.16.1
  script:
    - npm install

deploy_qa:
  image: node:12.16.1
  stage: deploy_qa
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/julia-qa.git HEAD:master
    - echo "Deployed to qa server"
  environment:  
    name: qa
    url: https://julia-qa.herokuapp.com/
  only:
    - master

test_qa:
  stage: test_qa
  image: trion/ng-cli-e2e
  script:
    - ENV=qa npm run wdioTest

deploy_production:
  image: node:12.16.1
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/julia-test-prod.git HEAD:master
    - echo "Deployed to production server"
  environment:  
    name: production
    url: https://julia-test-prod.herokuapp.com/
  only:
    - master
